### PR TITLE
Fix unterminated quoted string error when running podman v4

### PR DESCRIPTION
**Pull request by spikhoff**

### CODE REVIEW

**Comment by owtaylor** [comment]
I'm not sure why you closed the other pull request and opened this one. As I said in the other pull request, I'm not taking this patch until we have a https://github.com/containers/podman issue to reference in the commit message. Would you like me to file the issue? If so, can you provide your "rpm -q podman". Thanks!

**Comment by spikhoff** [comment]
Sorry, I messed up with rebasing, still learning how forking and contributing works :sweat_smile: 
That would be wonderful if you could open the issue.

```
podman-4.0.0-0.6.rc4.fc36.x86_64
```

**Review by owtaylor — CHANGES_REQUESTED** [review]
Could you update the commit message (git commit --amend) to be something like:

```
Fix unterminated quoted string error when running podman v4

Release candidates of podman v4 are unable to handle escape sequences inside strings.
See: https://github.com/containers/podman/issues/13446
Work around this by using the println function instead.
```

Then push the updated changes to your branch (git push --force <remote> main:main).

For future pull requests, it's better practice to use a specific branch in your repository for each pull request, rather than creating a pull request from changes on your main branch.

Thanks!

**Comment by owtaylor** [comment]
Thanks for the updated commit message! One more fix needed - can you update tests/test-basic.sh so that ./run-tests.sh passes (there are three copies of the 'podman inspect' command in that file)? Thanks!

**Review by owtaylor — APPROVED** [review]

**Pull request merged**
